- name: Update apt and uninstall Kerberos
  apt:
    name: "{{ packages }}"
    update_cache: yes
    autoclean: yes
    autoremove: yes
    purge: yes
    state: absent
  vars:
    packages:
    - krb5-kdc
    - krb5-admin-server
    - krb5-kdc-ldap
    - krb5-config
    - ldap-utils
    - krb5-user

- name: Remove extra dirs and files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/krb5kdc
    - /usr/local/bin/blksmanager
    - /etc/logrotate.d/logrotate_kerberos_backup

- name : Delete cron for kerberos_backup
  cron :
    name  : ansible_kerberos_backup
    cron_file: ansible_kerberos_backup
    state : absent