#!/bin/bash
# By: Tedezed

function usage {
cat <<EOF
Usage BLKS Manager
Options:

  -m <MODE> (add, delete)
  -l [HOST LDAP]
  -a <ADMIN LDAP>
  -w <ADMIN LDAP PASSWORD>
  -u <USERNAME>
  -p <USERNAME PASSWD>
  -g <GID>
  -d <DOMAIN>
  -e [PWEXPIRE]
  -k [KEYTAB FILE]

Example Add:
blksmanager -m add -l [HOST LDAP] -a (ADMIN_LDAP) -w (ADMIN_PASS_LDAP) -u (USER) -p (USER_PASSWD) -g (USER_GID_LDAP) -d (DOMAIN) -e [PWEXPIRE] -k [KEYTAB FILE]

Example Delete:
blksmanager -m delete -l [HOST LDAP] -a (ADMIN_LDAP) -w (ADMIN_PASS_LDAP) -u (USER) -d (DOMAIN) -k [KEYTAB FILE]

EOF
exit 2
}

function error ()
{
ERROR_CODE=$1
if [ $ERROR_CODE == 2000 ]; then
    ERROR_MSG="Error in mode '$MODE'"
elif [ $ERROR_CODE == 2001 ]; then
    ERROR_MSG="Mode add need: -a (ADMIN_LDAP) -w (ADMIN_PASS_LDAP) -u (USER) -p (USER_PASSWD) -g (USER_GID_LDAP) -d (DOMAIN)"
elif [ $ERROR_CODE == 2002 ]; then
    ERROR_MSG="Mode delete need: -a (ADMIN_LDAP) -w (ADMIN_PASS_LDAP) -u (USER) -d (DOMAIN)"
else
    ERROR_CODE="2404"
    ERROR_MSG="Error not found..."
    usage
fi
cat <<EOF
[ERROR $ERROR_CODE] $ERROR_MSG
EOF
}

# Source: https://www.openldap.org/lists/openldap-software/200110/msg00539.html
function getMaxUid ()
{
n=0
for i in $(ldapsearch -x -LLL $ldapsecret -h $HOST_IP -w $ADMIN_PASS -D "cn=$ADMIN, $ldapDN" "(uidNumber=*)" uidNumber -S uidNumber | grep uidNumber | tail -n1 );
do \
ldaparry[$n]=$i
let n+=1
done

    if [ "${ldaparry[0]}" == "uidNumber:" ]; then
    echo $((${ldaparry[1]}+1))
    return 0
    else
    echo $(("2001"))
    return 0
    fi
}

function add_to_ldap ()
{
ldapadd -h $HOST_IP -D "cn=$ADMIN,$ldapDN" -w $ADMIN_PASS << EOF
dn: uid=$USERNAME,cn=sudobase,cn=Workers,ou=SUDOers,$ldapDN
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
objectClass: person
uid: $USERNAME
sn: $USERNAME
givenName: $USERNAME
cn: $USERNAME
displayName: $USERNAME
uidNumber: $(getMaxUid)
gidNumber: $GID
gecos: $USERNAME
loginShell: /bin/bash
homeDirectory: /home/$USERNAME
EOF
ldapmodify -h $HOST_IP -D "cn=$ADMIN,$ldapDN" -w $ADMIN_PASS << EOF
dn: cn=sudobase,cn=Workers,ou=SUDOers,$ldapDN
changetype: modify
add: sudoUser
sudoUser: $USERNAME
EOF
}

function add_kerberos ()
{
echo "Use keytab: $KEYTAB"
if [ -z "$PWEXPIRE" ]; then
    kadmin.local -q "addprinc -pw $USERNAME_PASSWD $USERNAME@$UPPER_DOMAIN"
else
    kadmin.local -q "addprinc -pw $USERNAME_PASSWD -pwexpire \"$PWEXPIRE\" $USERNAME@$UPPER_DOMAIN"
fi
kadmin.local -q "ktadd -norandkey -k $KEYTAB $USERNAME@$UPPER_DOMAIN"
}

function del_ldap_kerberos ()
{
ldapdelete -h $HOST_IP -x -D "cn=$ADMIN,$ldapDN" "uid=$USERNAME,cn=sudobase,cn=Workers,ou=SUDOers,$ldapDN" -w $ADMIN_PASS

ldapmodify -h $HOST_IP -D "cn=$ADMIN, $ldapDN" -w $ADMIN_PASS << EOF
dn: cn=sudobase,cn=Workers,ou=SUDOers,$ldapDN
changetype: modify
delete: sudoUser
sudoUser: $USERNAME
EOF

kadmin.local -q "delete_principal $USERNAME@$UPPER_DOMAIN"
kdestroy
}

while getopts ":m:l:a:w:u:p:g:d:e:k:h" OPTIONS; do
        case "${OPTIONS}" in
                m) MODE=${OPTARG} ;;
                l) HOST_IP=${OPTARG} ;;
                a) ADMIN=${OPTARG} ;;
                w) ADMIN_PASS=${OPTARG} ;;
                u) USERNAME=${OPTARG} ;;
                p) USERNAME_PASSWD=${OPTARG} ;;
                g) GID=${OPTARG} ;;
                d) DOMAIN=${OPTARG} ;;
                e) PWEXPIRE=${OPTARG} ;;
                k) KEYTAB=${OPTARG} ;;
                h) usage ;;
                *) usage ;;
        esac
done

if [ -z "$KEYTAB" ]
then
    KEYTAB="/etc/krb5.keytab"
fi

if [ -z "$HOST_IP" ]
then
    HOST_IP="127.0.0.1"
fi

if [[ $MODE == "add" ]]
then
    if [ -z "$USERNAME" ] \
        || [ -z "$USERNAME_PASSWD" ] \
        || [ -z "$ADMIN" ] \
        || [ -z "$ADMIN_PASS" ] \
        || [ -z "$GID" ] \
        || [ -z "$DOMAIN" ]
    then
        error 2001
        usage
    else
        UPPER_DOMAIN=$(echo "$DOMAIN" | awk '{print toupper($0)}')
        DC1=$(echo "$DOMAIN" | cut -d"." -f1)
        DC2=$(echo "$DOMAIN" | cut -d"." -f2)
        DC3=$(echo "$DOMAIN" | cut -d"." -f3)

        ldapDN="dc=$DC1, dc=$DC2, dc=$DC3"

        add_to_ldap
        add_kerberos
    fi
elif [[ $MODE == "delete" ]]
then
    if [ -z "$USERNAME" ] \
        || [ -z "$ADMIN" ] \
        || [ -z "$ADMIN_PASS" ] \
        || [ -z "$DOMAIN" ]
    then
        error 2002
        usage
    else
        UPPER_DOMAIN=$(echo "$DOMAIN" | awk '{print toupper($0)}')
        DC1=$(echo "$DOMAIN" | cut -d"." -f1)
        DC2=$(echo "$DOMAIN" | cut -d"." -f2)
        DC3=$(echo "$DOMAIN" | cut -d"." -f3)

        ldapDN="dc=$DC1, dc=$DC2, dc=$DC3"

        del_ldap_kerberos
    fi
else
    error 2000
    usage
fi
