#!/bin/bash

DAYS_DELETE="10"
DATE_NOW=$(date +%d-%m-%Y)
BACKUP_PATH=/mnt/backups/kerberos

mkdir -p ${BACKUP_PATH}
cd ${BACKUP_PATH}

/usr/sbin/kdb5_util dump kdb5_${DATE_NOW}.dump

cp /etc/krb5.conf /etc/krb5_${DATE_NOW}.conf
cp /etc/krb5.keytab /etc/krb5_${DATE_NOW}.conf

tar -czf krb5kdc_etc_${DATE_NOW}.tar.gz /etc/krb5kdc
tar -czf krb5kdc_var_${DATE_NOW}.tar.gz /var/lib/krb5kdc

find ${BACKUP_PATH} -mtime  +$DAYS_DELETE -iname "*.dump" -exec rm -f {} \;
find ${BACKUP_PATH} -mtime  +$DAYS_DELETE -iname "*.conf" -exec rm -f {} \;
find ${BACKUP_PATH} -mtime  +$DAYS_DELETE -iname "*.tar.gz" -exec rm -f {} \;