- name: Update apt and uninstall Bind9
  apt:
    name: bind9
    autoclean: yes
    autoremove: yes
    purge: yes
    state: absent
    update_cache: yes

- name: Remove extra dirs and files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/bind
    - /etc/logrotate.d/logrotate_bind_backup

- name : Delete cron for bind_backup
  cron :
    name  : ansible_bind_backup
    cron_file: ansible_bind_backup
    state : absent