- name: Update apt and uninstall Bind9
  apt:
    name: bind9
    autoclean: yes
    autoremove: yes
    purge: yes
    state: absent
    update_cache: yes

- name: Recursively remove directory
  file:
    path: /etc/bind
    state: absent