- name: Install SSSD
  apt:
    name: "{{ sssd_packages }}"
    autoclean: yes
    autoremove: yes
    purge: yes
    update_cache: yes
    state: absent

- name: Recursively remove directory
  file:
    path: /etc/sssd
    state: absent

- name: Remove lines sss in file nsswtich for evit error in login with local users
  shell: sed -i 's/sss//' /etc/nsswitch.conf