---
- name: Interface IP
  debug:
    msg: 
      - "Interface IP: {{ hostvars['node-1'].ansible_host }}"

- name: Create /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: "/etc/resolv.conf"
